### ISSUE TITLE
"Learn more" link broken for "use @action, on, and fn instead of action" section

### ISSUE THREAD

**Issue by mikej** [ember-learn/ember-octane-vs-classic-cheat-sheet#20]
The "learn more" link here: 

<img width="839" alt="Screenshot 2019-12-09 at 09 33 33" src="https://user-images.githubusercontent.com/30024/70424611-8dbaba80-1a67-11ea-870d-74865b34b3cc.png">

links to https://octane-guides-preview.emberjs.com/release/components/actions-and-events/#toc_actions which is now a 404.

I had a quick look to try and find the current equivalent to link to and https://octane-guides-preview.emberjs.com/release/components/component-state-and-actions/#toc_html-modifiers-and-actions seems like the closest?

**Comment by jenweber** [comment]
Fixed, thank you for letting me know!
