### ISSUE TITLE
Default value for @args: falsy values

### ISSUE THREAD

**Issue by buschtoens** [ember-learn/ember-octane-vs-classic-cheat-sheet#21]
The code sample shown in [Specifying a default value for an argument](https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/#section-default-args) has a subtle potential bug.

```js
export default class MyComponent extends Component {
  get answer() {
    return this.args.answer || 42;
  }
}
```

When invoked with `false` or a falsy value, the argument will resolve to the default value of `42`:

```hbs
<MyComponent @answer={{false}} />
```

I just had a [Twitter thread](https://twitter.com/buschtoens/status/1204301874142334976) with @mehulkar about this and I think we should mention this caveat and show alternatives for these cases, e.g.:

[**Nullish Coalescing Operator**](https://github.com/tc39/proposal-nullish-coalescing)

```js
export default class MyComponent extends Component {
  get answer() {
    return this.args.answer ?? 42;
  }
}
```

Would resolve to the default value, if `@answer`

- is missing
- is `null`
- is `undefined`

[**`in` Operator**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in)

```js
export default class MyComponent extends Component {
  get answer() {
    return 'answer' in this.args ? this.args.answer : 42;
  }
}
```

Would resolve to the default value, if `@answer`

- is missing

If you think this'd be a good addition, I am happy to PR it! 💪

**Comment by jenweber** [comment]
Good catch! To keep things simple, I think we should choose a different example, perhaps showing strings, since this is a cheat sheet and it is meant to be very short. Then, we could cover the nuances of truthy/falsy args and defaults in the Guides. What are your thoughts?

**Comment by ijlee2** [comment]
Hi, @buschtoens. I want to let you know that the site will now show using `??` to provide a default argument. Thank you for the suggestion!

**Comment by buschtoens** [comment]
Great, thanks!
