### ISSUE TITLE
Improve mobile layout

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-octane-vs-classic-cheat-sheet#33]
Right now, if you look at this app on a phone, it squishes the code blocks in an unhelpful way. They should probably stack instead, and be left-right scrollable. Stacking is a good first step and scrolling could be a followup PR if you prefer.

All the styling for this app is held directly in this repository. You can do your work in the app/styles folder.

![Screen Shot 2020-05-17 at 1 57 40 PM](https://user-images.githubusercontent.com/16627268/82155957-67831d00-9846-11ea-9c6a-b0301a02d55d.png)

**Comment by ijlee2** [comment]
Many thanks to @Wolfr for helping out!
