### ISSUE TITLE
Bug - The "Classic" example for Element Modifiers is missing

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-octane-vs-classic-cheat-sheet#45]
This might just be a typo in the filename reference.

![Screen Shot 2020-06-23 at 11 31 21 PM](https://user-images.githubusercontent.com/16627268/85496073-b50f4a00-b5a9-11ea-9b06-c36d8f889e16.png)

**Comment by ijlee2** [comment]
For more context, I think the Element Modifiers section didn't have anything for Classic (since modifiers are best used with Glimmer components).

A possible solution to this issue is to better indicate in UI that something doesn't apply in either Classic or Octane.
