### ISSUE TITLE
Run deployments with GitHub Actions

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-octane-vs-classic-cheat-sheet#46]
Right now, we `ember deploy production` locally to deploy the app to GitHub pages. We could make this a GitHub Action instead! We already have GitHub actions running our tests, so this would be a small change.

The action should run only on merge to `master`.

**Comment by ijlee2** [comment]
I figured out how we can deploy to GitHub Pages via a workflow. I'll create a PR.
