### ISSUE TITLE
Remove commented out translations

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-octane-vs-classic-cheat-sheet#47]
In #43, I forgot to remove commented out translations. Please remove lines 19-96 (shown below).

https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/blob/b8d788733d79b9dfe19336aedbfe67105669d883/translations/fr-fr.yaml#L19-L96

**Comment by ChazJensen** [comment]
I'll take care of this real quick!
