### ISSUE TITLE
Add meta description for SEO

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-octane-vs-classic-cheat-sheet#57]
## Problem

A Lighthouse audit showed that we could improve our score by adding the meta description.

<img width="400" alt="lighthouse" src="https://user-images.githubusercontent.com/16869656/89791381-e061e000-dae8-11ea-9461-57edc7280177.png">

Please update `app/index.html` to include the following meta description:

```
See side-by-side examples of Ember Octane and Ember Classic
```

(I chose this description to match that in `package.json`. If there's a description that can help with SEO better, objectively, we can change the description in both `package.json` and `index.html`.)

## References

- https://moz.com/learn/seo/meta-description

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue labeled with `Hacktoberfest` in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by abraaoduarte** [comment]
I can help with this task

**Comment by ijlee2** [comment]
@abraaoduarte Thank you in advance for your help!

**Comment by abraaoduarte** [comment]
#60
