### ISSUE TITLE
Add pt-BR translations for recent updates

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-octane-vs-classic-cheat-sheet#68]
## Description

A few translations have been added to `en-us.yaml`. Let's create the corresponding translations for `pt-br.yaml`.

- [component.guide-section.edit-translation-text](https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/blob/227f76071287e37f9b5ab0be01042c8d007a2771/translations/en-us.yaml#L18)
- [component.locale-menu.select-your-preferred-language](https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/blob/227f76071287e37f9b5ab0be01042c8d007a2771/translations/en-us.yaml#L20)
- [component-properties.args.title](https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/blob/227f76071287e37f9b5ab0be01042c8d007a2771/translations/component-properties/args/en-us.yaml#L1)
- [component-properties.args.description](https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/blob/227f76071287e37f9b5ab0be01042c8d007a2771/translations/component-properties/args/en-us.yaml#L3-L6)

**Comment by ijlee2** [comment]
Hi, @fabriciotav. Can you help me with translating the texts above to `pt-BR` some time?

**Comment by ijlee2** [comment]
Hi, @bartocc. I hope you have been well. I was wondering if you may be interested in continuing to help with translating the Octane cheatsheet to `fr-FR`. Can you let me know?

**Comment by fabriciotav** [comment]
PR https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/pull/69 =D

**Comment by ijlee2** [comment]
@fabriciotav To help with translating, I sent you an invitation to receive `write` access to this repo. I'm hoping that this will allow you to make pull requests directly to this repo (and not to your fork) so that Percy and Netlify deploy preview may work.

**Comment by ijlee2** [comment]
The issue has been completed in #69.

Let me close this issue, @bartocc, but please feel free to leave a comment here or message me on Discord. Thanks!

**Comment by bartocc** [comment]
hi @ijlee2 👋 Sorry I did not update the fr-fr translation in a while

I'll try to find some time asap to work on this 👍

**Comment by ijlee2** [comment]
@bartocc Much thanks! If you have questions, please feel free to reach out.
