### ISSUE TITLE
Update or remove the `Accessing a route's model` example?

### ISSUE THREAD

**Issue by bertdeblock** [ember-learn/ember-octane-vs-classic-cheat-sheet#90]
[The example](https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/#routes__model-access) advises to use `@model` in route templates, but `@model` has a known bug:
https://github.com/emberjs/ember.js/issues/18987

After a while, an `ember-template-lint` rule was introduced to lint against using `@model` all together:
https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-model-argument-in-route-templates.md

The rule is not in the recommended config though (it was briefly).

Should we update or remove the example to avoid people running into this bug?

**Comment by ijlee2** [comment]
@bertdeblock Hello. Yes, I think we can update the example and the preceding paragraph, in case it can help developers avoid the aforementioned bug.

Can you open a pull request to:

- Update the paragraph to, something like,

     ```
     In a route template, '<code>'this.model'</code>' to access the result from the route's '<code>'model'</code>' hook.
     ```

- Update the code example.

As for translations to other languages, (based on a pattern match)

- Japanese:

    ```
    ルートテンプレートにおいて、ルートの'<code>'model'</code>'フックの結果にアクセスするために、'<code>'this.model'</code>'を使います。
    ```

- Portugese:

    ```
    No template de uma rota, use '<code>'this.model'</code>' para acessar o resultado do hook '<code>'model'</code>' da rota.
    ```
- Spanish:

    ```
    En un template de ruta, utilice '<code>'this.model'</code>' para acceder al resultado del '<code>'model'</code>' hook de la ruta.
    ```

**Comment by ijlee2** [comment]
@jenweber Do you have a different opinion or suggestion, as to showing `this.model` instead of `@model`?

**Comment by jenweber** [comment]
This is very interesting and surprising. Thanks for bringing it up. I know that the mental model of Ember is to use `@model` because `@` signifies that info is coming in from somewhere else. When you are referencing model in a route template, you are receiving the model from the controller, so it's best understood as `@`.

I am somewhat conflicted because the guides and tutorial all teach `@model`, but also there's this linting rule. I posted a question in dev-ember-js discord chat. Depending on what they say, we will either leave this as `@model` or change it to `this.model` here, and in the guides, and in the tutorial.

**Comment by jenweber** [comment]
Another option is we could add a small note here that some people use this.model if they run into problems, since it is still supported. This cheatsheet is intended for a different audience than the Guides.

**Comment by ijlee2** [comment]
@jenweber Thanks for providing your feedback. I also think it's a good idea to check first with others on the `#dev-ember-js` channel.

**Comment by jenweber** [comment]
I should add, if we don't get an answer from the framework core team, I prefer adding a note compared to changing them all to this.model, but that opinion is non-blocking. Both are supported, as far as I know. The Ember 4 blog post doesn't say anything about changing model handling in templates.

**Comment by bertdeblock** [comment]
I think we can close this? The consensus is still that `@model` should be used and teached and that the bug needs to be addressed. What do you guys think?

**Comment by ijlee2** [comment]
@bertdeblock Closing the issue sounds good with me. Jen?

Thank you both for following up on asking the core teams.

**Comment by jenweber** [comment]
Sounds good!

**Comment by jenweber** [comment]
Thanks again for raising this issue!
